steps:
  - id: "Rodando docker-composer"
    name: 'gcr.io/$PROJECT_ID/docker-compose:1.14.0'
    args: [ '-f', 'docker-compose.cloudbuild.yaml', 'up', '-d' ]

  - id: "Rodando docker ps"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'ps' ]
