steps:
  - id: "Running docker-compose"
    name: 'docker/compose'
    args: [ '-f', 'docker-compose.cloudbuild.yaml', 'up', '-d' ]

  - id: "Running docker ps"
    name: 'docker'
    args: [ 'ps' ]

  - id: "Running composer"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'composer', 'install' ]

  - id: "Coping .env file"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'cp', '.env.example', '.env' ]

  - id: "Running key generate"
    name: 'docker'
    args: [ 'exec', '-t', 'app', '/var/www/artisan', 'key:generate' ]

  - id: "Running migrations"
    name: 'docker'
    args: [ 'exec', '-t', 'app', '/var/www/artisan', 'migrate' ]

  - id: "Running phpunit"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml' ]
