steps:
  - id: "Running docker-composer"
    name: 'docker/compose'
    args: [ '-f', 'docker-compose.cloudbuild.yaml', 'up', '-d' ]

  - id: "Running docker ps"
    name: 'docker'
    args: [ 'ps' ]

  - id: "Running composer"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'composer', 'install' ]

  - id: "Running phpunit"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml' ]
