steps:
  - id: "Rodando docker-composer"
    name: 'docker/compose'
    args: [ '-f', 'docker-compose.cloudbuild.yaml', 'up', '-d' ]

  - id: "Rodando docker ps"
    name: 'docker'
    args: [ 'ps' ]
