apiVersion: v1
kind: Service
metadata:
  name: app-service # this will be the internal hostname
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9000
      nodePort: 30050 # must be higher than 30000
  selector:
    app: app
